### ISSUE TITLE
Need to compile manually on MacOS

### ISSUE THREAD

**Issue by TimDurward** [Paperspace/terraform-provider-paperspace#1]
Using the Makefile I'll get an error trying to run `Terraform apply` or other Terraform CRUD actions:
`*terraform.EvalInitProvider, err: fork/exec ...  exec format error`  

There is no support in the Makefile for other Architectures / Operating Systems (My Mac included)

So after compiling manually with Mac compatible parameters, I was able to run terraform apply with paperspace provider. 

Figured I'd note it here, if anyone else was running into this. 

This could probably be fixed by removing hardcoded environment variables for GOOS=linux GOARCH=amd64 and assume users running `go build` have values exported to their shell, or Golang resolves them.

**Comment by jaredscheib** [comment]
Hi @TimDurward, this has been resolved as of 0300151496aa6c15974428bb472809339aac6596 :) Better late than never! We've picked back up development on this recently. If you happen to still be using this provider or do, and find any other issues, we'd love to hear from ya~
